{
  "comments": [
    {
      "key": {
        "uuid": "091ddcad_cbb6d0a1",
        "filename": "src/config/api-server/vnc_cfg_api_server/db_manage.py",
        "patchSetId": 2
      },
      "lineNbr": 1058,
      "author": {
        "id": 64
      },
      "writtenOn": "2020-04-28T00:42:18Z",
      "side": 1,
      "message": "I suppose CI might fail as the line exceeds 79 char limit in a line.",
      "revId": "137a578f24cf81ec135e83ceab696096710396e5",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}