{
  "comments": [
    {
      "key": {
        "uuid": "6613d3ee_ae95bd2a",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/virtual_machine_interface.py",
        "patchSetId": 1
      },
      "lineNbr": 276,
      "author": {
        "id": 64
      },
      "writtenOn": "2019-11-14T18:51:22Z",
      "side": 0,
      "message": "This change was introduced to fix CEM-4815. So removing this might bring in this failure? Could you revisit.",
      "revId": "b7d25e0ff61ab4d6811b32b4103bc9590a8bdffa",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}