---
- name: Delete fabric and all the devices in the fabric
  hosts: localhost
  connection: local
  tasks:
    - set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':2, 'task_weightage_array':[10, 90] })}}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Deleting fabric and all the devices in the fabric"

    - name: delete fabric and devices in it
      set_fact:
        output: "{{ job_ctx | delete_devices }}"

    - debug: var=output

    - name: check failure
      include_tasks: error_handler.yml
      when: output.status == 'failure'
      vars:
        op_err_message: "Unable to delete fabric due to error"
        jl_err_message: "Failed to delete fabric {{ playbook_input.input.fabric_fq_name }} due to error. Here is deletion log\n: {{ output.deletion_log }}"
        results:
          fabric_uuid: "{{ playbook_input.input.fabric_fq_name }}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 2
        jl_message: "Successfully deleted fabric: {{ playbook_input.input.fabric_fq_name }}"
